"""
Shared utilities for HeatSentinal Phase 1 satellite processing scripts.

Used by:
    process_landsat_lst.py
    process_sentinel_ndvi.py
    process_land_cover.py
    process_elevation.py
    build_phase1_dataset.py

Everything here is read-only with respect to the master grid: it never
creates a new grid, it only indexes the existing one so that satellite
rasters (30m Landsat, 10m Sentinel-2, etc.) can be aggregated onto it
without a Python loop over every one of the ~600,000 cells.

GRID ALIGNMENT TRICK (why this is fast)
----------------------------------------
backend/data/ncr_300m_grid.gpkg was generated by generate_ncr_grid.py using
box(x, y, x+300, y+300) tiles whose corners sit on exact multiples of 300m
in EPSG:6933 (World Cylindrical Equal Area), starting from an origin of
(0, 0) in that CRS. That means:

    col = round((centroid_x - 150) / 300)
    row = round((centroid_y - 150) / 300)

are GLOBAL integer grid coordinates for every cell -- no need to know the
grid's bounding box to compute them.

When we reproject+resample a source raster (Landsat 30m, Sentinel-2 10m,
NASADEM 30m) into EPSG:6933 at a resolution that evenly divides 300
(30 -> 10x10 blocks, 10 -> 30x30 blocks) AND we snap the destination
transform's origin to a multiple of 300m, every block of NxN resampled
pixels lands on exactly one 300m grid cell. We can then reshape the
resampled array into blocks and reduce with vectorized NumPy
(nanmean/nanmedian/nanstd/nanmin/nanmax/count) -- no per-cell loop, no
per-scene loop over cells, and it's all done in memory with arrays sized
to one Landsat/Sentinel scene at a time, not the whole NCR grid.
"""

from __future__ import annotations

import json
import time
import traceback
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional

import numpy as np
import pandas as pd

# ============================================================
# PATHS (relative to repo root; do not hardcode absolute paths)
# ============================================================

REPO_ROOT = Path(__file__).resolve().parent
BOUNDARY_FILE = REPO_ROOT / "backend" / "data" / "ncr_boundary.geojson"
GRID_GPKG = REPO_ROOT / "backend" / "data" / "ncr_300m_grid.gpkg"
GRID_LAYER = "ncr_300m_grid"
PHASE1_DIR = REPO_ROOT / "backend" / "data" / "phase1"

GRID_SIZE_M = 300
GRID_CRS = "EPSG:6933"          # metric CRS the master grid is stored in
WGS84 = "EPSG:4326"

# Used to pack (col, row) grid indices into a single int64 lookup key.
# Grid indices for NCR (EPSG:6933 meters / 300) run well under 1e8, so
# this multiplier leaves headroom with no risk of collision or overflow.
_GRID_KEY_MULT = 1_000_000_000


# ============================================================
# GRID INDEX
# ============================================================

@dataclass
class GridIndex:
    """Maps global (col, row) 300m grid coordinates -> cell_id."""

    key_to_cell: pd.Series   # index = grid_key (int64), values = cell_id
    n_cells: int

    @staticmethod
    def col_row_from_xy(centroid_x: np.ndarray, centroid_y: np.ndarray):
        col = np.round((centroid_x - GRID_SIZE_M / 2) / GRID_SIZE_M).astype(np.int64)
        row = np.round((centroid_y - GRID_SIZE_M / 2) / GRID_SIZE_M).astype(np.int64)
        return col, row

    @staticmethod
    def make_key(col: np.ndarray, row: np.ndarray) -> np.ndarray:
        return col.astype(np.int64) * _GRID_KEY_MULT + row.astype(np.int64)

    def lookup(self, col: np.ndarray, row: np.ndarray) -> np.ndarray:
        """Vectorized (col,row) -> cell_id. Returns None (object dtype) where
        the block does not correspond to any NCR grid cell."""
        keys = self.make_key(col, row)
        return self.key_to_cell.reindex(keys).to_numpy()


def load_master_grid():
    """Load the existing 300m master grid. Raises with a clear message if
    it hasn't been generated yet -- callers should not silently create a
    new one."""
    import geopandas as gpd

    if not GRID_GPKG.exists():
        raise FileNotFoundError(
            f"Master grid not found at {GRID_GPKG}.\n"
            "Run `python generate_ncr_grid.py` first (Task 2) -- "
            "this script does not create a grid."
        )

    grid = gpd.read_file(GRID_GPKG, layer=GRID_LAYER)
    if grid.crs is None or grid.crs.to_string() != GRID_CRS:
        grid = grid.to_crs(GRID_CRS)

    required_cols = {"cell_id", "centroid_x", "centroid_y", "geometry"}
    missing = required_cols - set(grid.columns)
    if missing:
        raise RuntimeError(
            f"Master grid is missing expected column(s): {sorted(missing)}. "
            "Was it generated by the current generate_ncr_grid.py?"
        )

    if grid["cell_id"].duplicated().any():
        n_dupe = int(grid["cell_id"].duplicated().sum())
        raise RuntimeError(f"Master grid has {n_dupe} duplicate cell_id values.")

    return grid


def build_grid_index(grid) -> GridIndex:
    col, row = GridIndex.col_row_from_xy(
        grid["centroid_x"].to_numpy(dtype=np.float64),
        grid["centroid_y"].to_numpy(dtype=np.float64),
    )
    keys = GridIndex.make_key(col, row)
    series = pd.Series(grid["cell_id"].to_numpy(), index=keys)
    if series.index.duplicated().any():
        raise RuntimeError(
            "Grid index collision: two grid cells mapped to the same "
            "(col,row). This should not happen for a regular 300m tiling; "
            "the master grid may be corrupt."
        )
    return GridIndex(key_to_cell=series, n_cells=len(series))


def snapped_bounds(minx, miny, maxx, maxy, size=GRID_SIZE_M):
    """Expand a bounding box outward to the nearest multiple of `size`,
    so a destination raster transform built from it aligns exactly with
    the 300m grid."""
    return (
        np.floor(minx / size) * size,
        np.floor(miny / size) * size,
        np.ceil(maxx / size) * size,
        np.ceil(maxy / size) * size,
    )


def aggregate_aligned_array(values: np.ndarray, block: int):
    """Reshape a (rows, cols) array -- whose rows/cols are each exactly
    divisible by `block` and whose georeferencing origin is snapped to a
    300m multiple -- into 300m blocks and reduce with NaN-aware stats.

    `values` must already have NaN in place of nodata/masked pixels.

    Returns dict of 2D arrays (n_block_rows, n_block_cols): mean, median,
    std, min, max, count. `count` is the number of valid source pixels
    that fell in that 300m cell (used as the observation count).
    """
    rows, cols = values.shape
    if rows % block != 0 or cols % block != 0:
        raise ValueError(
            f"Array shape {values.shape} is not divisible by block size {block}; "
            "the caller must pad/crop to a block-aligned shape first."
        )

    n_br, n_bc = rows // block, cols // block
    reshaped = values.reshape(n_br, block, n_bc, block).transpose(0, 2, 1, 3)
    reshaped = reshaped.reshape(n_br, n_bc, block * block)

    count = np.sum(~np.isnan(reshaped), axis=2)
    with np.errstate(all="ignore"), warnings.catch_warnings():
        # Blocks with zero valid pixels legitimately produce all-NaN
        # reductions (e.g. a 300m cell entirely outside a scene's cloud
        # mask) -- that's expected, not a bug, so silence NumPy's warning
        # for it rather than letting it spam stdout per scene.
        warnings.filterwarnings("ignore", category=RuntimeWarning)
        mean = np.nanmean(reshaped, axis=2)
        median = np.nanmedian(reshaped, axis=2)
        std = np.nanstd(reshaped, axis=2)
        vmin = np.nanmin(np.where(count[..., None] > 0, reshaped, np.nan), axis=2)
        vmax = np.nanmax(np.where(count[..., None] > 0, reshaped, np.nan), axis=2)

    return {
        "mean": mean, "median": median, "std": std,
        "min": vmin, "max": vmax, "count": count,
    }


def majority_aligned_array(values: np.ndarray, block: int, valid_classes: list[int]):
    """Like aggregate_aligned_array but for categorical rasters: returns
    the dominant (mode) class and its fraction within each 300m cell,
    ignoring pixels whose class is not in valid_classes (nodata/masked).

    Uses a small lookup table to remap raw class codes -> compact indices,
    NOT np.isin(). For a several-hundred-million-pixel raster (this
    collection's tiles are enormous), np.isin's internal sort-based
    implementation allocates an int64 array sized to the *entire* input
    (confirmed: a 915M-pixel tile crashed trying to allocate 6.82 GiB for
    exactly that) -- a LUT indexed by pixel value costs nothing close to
    that regardless of raster size, since land-cover codes are always a
    handful of small integers.
    """
    rows, cols = values.shape
    if rows % block != 0 or cols % block != 0:
        raise ValueError(
            f"Array shape {values.shape} is not divisible by block size {block}."
        )
    n_br, n_bc = rows // block, cols // block

    min_v = int(min(valid_classes + [int(values.min())]))
    max_v = int(max(valid_classes + [int(values.max())]))
    lut = np.full(max_v - min_v + 1, -1, dtype=np.int16)
    for i, c in enumerate(valid_classes):
        lut[c - min_v] = i
    compact = lut[values - min_v]   # -1 where masked/invalid, else 0..K-1
    del lut

    reshaped = compact.reshape(n_br, block, n_bc, block).transpose(0, 2, 1, 3)
    reshaped = reshaped.reshape(n_br, n_bc, block * block)
    del compact

    K = len(valid_classes)
    counts = np.zeros((n_br, n_bc, K), dtype=np.int32)
    for i in range(K):
        counts[:, :, i] = np.sum(reshaped == i, axis=2)
    del reshaped

    valid_total = counts.sum(axis=2)
    best_idx = np.argmax(counts, axis=2)
    best_count = np.take_along_axis(counts, best_idx[..., None], axis=2)[..., 0]
    dom_class = np.array(valid_classes, dtype=np.int16)[best_idx]
    with np.errstate(invalid="ignore", divide="ignore"):
        dom_frac = np.where(valid_total > 0, best_count / np.maximum(valid_total, 1), 0.0)
    dom_class = np.where(valid_total > 0, dom_class, -1)

    return {"dominant_class": dom_class, "fraction": dom_frac.astype(np.float32),
            "valid_count": valid_total}


# ============================================================
# PLANETARY COMPUTER: SEARCH + SIGNED, RETRYING RASTER ACCESS
# ============================================================

PC_STAC_URL = "https://planetarycomputer.microsoft.com/api/stac/v1"


def open_pc_catalog():
    """pystac_client Client pre-wired to auto-sign asset URLs."""
    import planetary_computer
    from pystac_client import Client

    return Client.open(PC_STAC_URL, modifier=planetary_computer.sign_inplace)


def retry(fn: Callable, attempts: int = 3, delay_seconds: float = 2.0, label: str = ""):
    """Run fn() with up to `attempts` tries. Raises the last exception
    (with a full traceback string attached) if every attempt fails --
    never swallows the real error."""
    last_exc = None
    for i in range(1, attempts + 1):
        try:
            return fn()
        except Exception as exc:  # noqa: BLE001 -- we re-raise below
            last_exc = exc
            print(f"    [retry {i}/{attempts}] {label} failed: {exc!r}")
            if i < attempts:
                time.sleep(delay_seconds)
    assert last_exc is not None
    raise RuntimeError(
        f"{label} failed after {attempts} attempts.\n"
        f"{''.join(traceback.format_exception(type(last_exc), last_exc, last_exc.__traceback__))}"
    ) from last_exc


def gdal_retry_env():
    """rasterio.Env kwargs that make GDAL's own HTTP/VSICURL layer retry
    transient network failures before rasterio even sees an exception."""
    return dict(
        GDAL_HTTP_MAX_RETRY=3,
        GDAL_HTTP_RETRY_DELAY=1,
        GDAL_DISABLE_READDIR_ON_OPEN="EMPTY_DIR",
        CPL_VSIL_CURL_ALLOWED_EXTENSIONS=".tif,.TIF,.tiff",
        GDAL_CACHEMAX=512,
    )


# ============================================================
# CHECKPOINT / SCENE CACHE
# ============================================================

class Checkpoint:
    """Tracks which scenes have already been processed so a run can be
    interrupted (Ctrl+C, crash, network outage) and resumed without
    re-downloading completed scenes."""

    def __init__(self, path: Path):
        self.path = path
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.state = self._load()

    def _load(self) -> dict:
        if self.path.exists():
            try:
                return json.loads(self.path.read_text())
            except json.JSONDecodeError:
                print(f"    Checkpoint file {self.path} is corrupt -- starting fresh.")
        return {"completed": {}, "failed": {}}

    def is_done(self, scene_id: str) -> bool:
        return scene_id in self.state["completed"]

    def mark_done(self, scene_id: str, meta: dict):
        self.state["completed"][scene_id] = meta
        self.state["failed"].pop(scene_id, None)
        self._save()

    def mark_failed(self, scene_id: str, error: str):
        self.state["failed"][scene_id] = error
        self._save()

    def _save(self):
        self.path.write_text(json.dumps(self.state, indent=2, default=str))


def cache_path_for(cache_dir: Path, scene_id: str, suffix: str = ".npz") -> Path:
    cache_dir.mkdir(parents=True, exist_ok=True)
    safe_id = scene_id.replace("/", "_")
    return cache_dir / f"{safe_id}{suffix}"


# ============================================================
# SUMMARY / DATA-QUALITY HELPERS (shared by build_phase1_dataset.py)
# ============================================================

def field_quality_report(series: pd.Series, valid_range: Optional[tuple] = None) -> dict:
    total = len(series)
    numeric = pd.to_numeric(series, errors="coerce")
    valid = numeric.notna()
    if valid_range is not None:
        lo, hi = valid_range
        out_of_range = valid & ((numeric < lo) | (numeric > hi))
        valid &= ~out_of_range
    else:
        out_of_range = pd.Series(False, index=series.index)

    n_valid = int(valid.sum())
    report = {
        "total_cells": total,
        "valid_cells": n_valid,
        "missing_cells": int(total - numeric.notna().sum()),
        "out_of_range_cells": int(out_of_range.sum()),
        "coverage_pct": round(100.0 * n_valid / total, 2) if total else 0.0,
        "min": float(numeric[valid].min()) if n_valid else None,
        "max": float(numeric[valid].max()) if n_valid else None,
        "mean": float(numeric[valid].mean()) if n_valid else None,
        "median": float(numeric[valid].median()) if n_valid else None,
    }
    return report
